# Generated by Django 4.0.6 on 2022-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_name', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DecimalField(decimal_places=2, max_digits=5)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
