# Generated by Django 4.0.6 on 2022-10-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
