# Generated by Django 4.0.6 on 2022-10-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
