# Generated by Django 4.0.6 on 2022-10-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_user_id_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
