# Generated by Django 4.0.6 on 2022-10-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_movieimage'),
        ('base', '0010_favorite_user'),
    ]

    operations = [
    ]
