# Generated by Django 4.0.6 on 2022-10-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_movieimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
