# Generated by Django 4.0.6 on 2022-10-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_movie_movie_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='_id',
            new_name='favoriteid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='_id',
            new_name='movieid',
        ),
    ]
