# Generated by Django 4.0.6 on 2022-10-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename__id_favorite_favoriteid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favoriteid',
            new_name='favorite_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movieid',
            new_name='movie_id',
        ),
    ]
