# Generated by Django 4.0.6 on 2022-10-20 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0015_rename_favoriteid_favorite_favorite_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('movie_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('time_ordered', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
