# Generated by Django 4.0.6 on 2022-11-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
